Repository metal3-io/ip-address-manager, pull requests merged in 2021-11, with the labels that each got.

#68 ⚠️ Adapt IPAM for CAPI v1beta1
  README.md
  api/go.mod
  api/go.sum
  controllers/ippool_controller.go
  controllers/ippool_controller_test.go
  controllers/suite_test.go
  go.mod
  go.sum
  ipam/ippool_manager.go
  ipam/ippool_manager_test.go
  ipam/mocks/zz_generated.ippool_manager.go
  main.go
Labels: approved, lgtm, size/XL

#72 ✨ Uplift/controller runtime v0.10.3 and cluster-api to v1.0.1
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#74 :sparkles: Update the contract labels for IPAM CRDS
  config/crd/kustomization.yaml
Labels: approved, lgtm, size/XS
