Repository metal3-io/ip-address-manager, pull requests merged in 2021-07, with the labels that each got.

#37 ⚠️ Accomodate CAPI v1a4 related changes
  Makefile
  api/go.mod
  api/go.sum
  api/v1alpha1/ipaddress_webhook.go
  api/v1alpha1/ipclaim_webhook.go
  api/v1alpha1/ippool_webhook.go
  config/certmanager/certificate.yaml
  config/crd/bases/ipam.metal3.io_ipaddresses.yaml
  config/crd/bases/ipam.metal3.io_ipclaims.yaml
  config/crd/bases/ipam.metal3.io_ippools.yaml
  config/default/kustomization.yaml
  config/default/kustomizeconfig.yaml
  config/default/manager_image_patch.yaml
  config/default/manager_pull_policy_patch.yaml
  config/default/manager_webhook_patch.yaml
  config/default/webhookcainjection_patch.yaml
  config/kustomization.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manager/manager_auth_proxy_patch.yaml
  config/patch_crd_webhook_namespace.yaml
  config/rbac/auth_proxy_role.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/kustomization.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
  config/webhook/kustomization.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/manifests.yaml
  controllers/ippool_controller.go
  controllers/ippool_controller_test.go
  controllers/suite_test.go
  go.mod
  go.sum
  hack/codegen.sh
  hack/tools/go.mod
  hack/tools/go.sum
  ipam/ippool_manager.go
  ipam/ippool_manager_test.go
  ipam/manager_factory_test.go
  ipam/mocks/zz_generated.ippool_manager.go
  ipam/suite_test.go
  ipam/utils.go
  main.go
Labels: size/XXL

#42 📖 Update documentation with latest changes
  README.md
  docs/api.md
Labels: approved, lgtm, size/S

#40 Update CAPI to latest stable version
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#38 :running: remove dhellmann from owners
  OWNERS
Labels: approved, lgtm, size/XS

#41 🐛 Fix examples generation
  examples/generate.sh
  examples/ippool/ippool.yaml
Labels: approved, lgtm, size/S
