Repository metal3-io/ip-address-manager, pull requests merged in 2021-08, with the labels that each got.

#43 Update IPAM compatibility with CAPI in notes
  README.md
Labels: approved, lgtm, size/XS

#44 ✨ Uplift CAPI to 0.4.2
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#45 🐛 Webhook reg should accept both v1 and v1beta1 admissions
  api/v1alpha1/ipaddress_webhook.go
  api/v1alpha1/ipclaim_webhook.go
  api/v1alpha1/ippool_webhook.go
  config/webhook/manifests.yaml
Labels: approved, lgtm, size/S
