Repository metal3-io/ip-address-manager, pull requests merged in 2021-12, with the labels that each got.

#77 🌱 Use golang image as base for unit test containers
  hack/unit.sh
Labels: approved, lgtm, size/XS

#79 🌱Bump controller-runtime to v0.11.0
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#80 🐛Fix unrelated capm3 mentions under hack folder scripts
  hack/gofmt.sh
  hack/govet.sh
  hack/unit.sh
Labels: approved, lgtm, size/S

#78 🌱Use golang as base image and fix capm3 mentions
  hack/gofmt.sh
  hack/govet.sh
  hack/unit.sh
Labels: approved, lgtm, size/S

#81 🐛Fix unrelated capm3 mentions under hack folder scripts
  hack/gofmt.sh
  hack/govet.sh
  hack/unit.sh
Labels: approved, lgtm, size/S

#73 🐛 Update examples generation after v1beta1 uplift
  Makefile
  config/default/manager_image_patch.yaml
  examples/generate.sh
  examples/ippool/ippool.yaml
  hack/hack/kind_with_registry.sh
Labels: approved, lgtm, size/L
