Repository metal3-io/ip-address-manager, pull requests merged in 2021-03, with the labels that each got.

#24 🏃Rename shortNames with prefix 'm3' or 'metal3'
  api/v1alpha1/ipaddress_types.go
  api/v1alpha1/ipclaim_types.go
  api/v1alpha1/ippool_types.go
  config/crd/bases/ipam.metal3.io_ipaddresses.yaml
  config/crd/bases/ipam.metal3.io_ipclaims.yaml
  config/crd/bases/ipam.metal3.io_ippools.yaml
Labels: approved, lgtm, ok-to-test, size/S

#23 🏃 Bump the Golang version to 1.16
  Dockerfile
  Makefile
  go.mod
  hack/Dockerfile.unit
  hack/codegen.sh
  hack/ensure-go.sh
  hack/gofmt.sh
  hack/govet.sh
  hack/tools/go.mod
Labels: approved, lgtm, size/S

#26 🌱 Update golangci-lint to latest
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/XL
