Repository metal3-io/ip-address-manager, pull requests merged in 2021-09, with the labels that each got.

#46 🏃 Add Feruz and Furkat as approvers
  OWNERS
Labels: approved, lgtm, size/XS

#48 ✨ Uplift controller tools to v0.6.2
  config/crd/bases/ipam.metal3.io_ipaddresses.yaml
  config/crd/bases/ipam.metal3.io_ipclaims.yaml
  config/crd/bases/ipam.metal3.io_ippools.yaml
  hack/tools/go.mod
  hack/tools/go.sum
  ipam/mocks/zz_generated.ippool_manager.go
  ipam/mocks/zz_generated.manager_factory.go
Labels: approved, lgtm, size/L

#47 ✨ Add webhook readiness and health check
  main.go
Labels: approved, lgtm, size/XS

#50 🌱 Opt for a more inclusive Other PR category
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  VERSIONING.md
  hack/tools/release/notes.go
Labels: approved, lgtm, size/S

#49 ✨ Uplift controller runtime to latest
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#51 ✨ Add AGE column to IPAM CRDs
  api/v1alpha1/ipaddress_types.go
  api/v1alpha1/ipclaim_types.go
  api/v1alpha1/ippool_types.go
  config/crd/bases/ipam.metal3.io_ipaddresses.yaml
  config/crd/bases/ipam.metal3.io_ipclaims.yaml
  config/crd/bases/ipam.metal3.io_ippools.yaml
Labels: approved, lgtm, size/S

#54 🌱 Remove .travis.yml config
  .travis.yml
Labels: approved, lgtm, size/S

#56 ✨ Uplift controller runtime, controller-tools and cluster-api
  api/go.mod
  api/go.sum
  config/crd/bases/ipam.metal3.io_ipaddresses.yaml
  config/crd/bases/ipam.metal3.io_ipclaims.yaml
  config/crd/bases/ipam.metal3.io_ippools.yaml
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/XL

#57 🐛 Fix CVE-2021-20329
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/M

#53 🐛 Fix API version in IPAM webhooks
  api/v1alpha1/ipaddress_webhook.go
  api/v1alpha1/ipclaim_webhook.go
  api/v1alpha1/ippool_webhook.go
  config/webhook/manifests.yaml
Labels: approved, lgtm, size/M

#58 🐛 Fix CVE-2021-20329
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/M

#59 🐛 Fix kustomize bin usage in Makefile
  Makefile
Labels: approved, lgtm, size/XS
