Repository metal3-io/ip-address-manager, pull requests merged in 2022-08, with the labels that each got.

#125 🌱 Dependencies uplift (capi,controller runtime, k8s.io/*)
  api/go.mod
  api/go.sum
  config/crd/bases/ipam.metal3.io_ipaddresses.yaml
  config/crd/bases/ipam.metal3.io_ipclaims.yaml
  config/crd/bases/ipam.metal3.io_ippools.yaml
  config/manager/manager.yaml
  controllers/suite_test.go
  examples/provider-components/manager_tolerations_patch.yaml
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  main.go
Labels: size/XXL

#128 🐛 Always patch IPClaim
  ipam/ippool_manager.go
Labels: approved, lgtm, size/S

#129 🌱 Move fmuyassarov to emeritus_approvers
  OWNERS
Labels: approved, lgtm, size/XS

#130 🌱 Add golangci-lint file
  .golangci.yaml
  api/v1alpha1/common_types.go
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/ipaddress_types.go
  api/v1alpha1/ipaddress_webhook.go
  api/v1alpha1/ipaddress_webhook_test.go
  api/v1alpha1/ipclaim_types.go
  api/v1alpha1/ipclaim_webhook.go
  api/v1alpha1/ipclaim_webhook_test.go
  api/v1alpha1/ippool_types.go
  api/v1alpha1/ippool_webhook.go
  api/v1alpha1/ippool_webhook_test.go
  api/v1alpha1/utils.go
  config/crd/bases/ipam.metal3.io_ipaddresses.yaml
  config/crd/bases/ipam.metal3.io_ipclaims.yaml
  config/crd/bases/ipam.metal3.io_ippools.yaml
  controllers/ippool_controller.go
  controllers/ippool_controller_test.go
  controllers/suite_test.go
  hack/ensure-golangci-lint.sh
  ipam/ippool_manager.go
  ipam/ippool_manager_test.go
  ipam/manager_factory.go
  ipam/requeue_error.go
  ipam/suite_test.go
  ipam/utils.go
  ipam/utils_test.go
  main.go
Labels: approved, lgtm, size/L

#127 🌱 Protect IPAddresses and IPClaims from accidental deletion
  controllers/ippool_controller.go
  ipam/ippool_manager.go
  ipam/ippool_manager_test.go
Labels: approved, lgtm, size/L
