Repository metal3-io/ip-address-manager, pull requests merged in 2022-09, with the labels that each got.

#133 🌱 Use finalizers instead of ownerRefs to check if IPClaim is in use
  ipam/ippool_manager.go
  ipam/ippool_manager_test.go
Labels: approved, lgtm, size/S

#131 🌱 Increase linter timeout
  Makefile
  hack/unit.sh
Labels: approved, lgtm, size/S

#119 🐛 Don't consider IPAddresses in use when IPPool is being deleted
  ipam/ippool_manager.go
  ipam/ippool_manager_test.go
Labels: approved, lgtm, size/M

#132 🌱 Improve logging when releasing address
  controllers/ippool_controller_test.go
  ipam/ippool_manager.go
  ipam/ippool_manager_test.go
  ipam/manager_factory_test.go
Labels: approved, lgtm, size/M

#138 🌱 Move namnx228 to emeritus reviewers
  OWNERS
Labels: approved, lgtm, size/XS

#139 🌱 Add gomod script for prow test and fix gosec script to use correct name as workdir
  go.mod
  go.sum
  hack/gomod.sh
  hack/gosec.sh
Labels: approved, lgtm, size/L

#143 🌱 Move namnx228 to emeritus reviewers
  OWNERS
Labels: approved, lgtm, size/XS

#136 🌱 Downgrade k8s modules to v0.24.2 in go modules and Uplift CAPI to v1.2.2
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#149 🐛 Fix Makefile target: kind-create problem
  hack/kind_with_registry.sh
Labels: approved, lgtm, size/XS

#146 📖 Update IPAM compatibility table
  README.md
Labels: approved, lgtm, size/XS
