Repository metal3-io/ip-address-manager, pull requests merged in 2022-10, with the labels that each got.

#154 🌱 uplift capi to v1.2.3
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#155 🌱 Bump golang to v1.18
  .github/workflows/release.yaml
  .golangci.yaml
  Dockerfile
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/Dockerfile.unit
  hack/codegen.sh
  hack/ensure-golangci-lint.sh
  hack/gofmt.sh
  hack/gomod.sh
  hack/govet.sh
  hack/unit.sh
Labels: approved, lgtm, size/L

#156 🌱 Uplift capi to v1.2.4
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#157 🌱 Fix go mod vulnerabilities according to different CVEs
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#158 🌱 Fix go mod vulnerabilities according to different CVEs
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/M

#160 🌱 Fix vulnerabilities also in hack/tools
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/S

#159 🌱 Fix go mod vulnerabilities according to different CVEs
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/M
