Repository metal3-io/ip-address-manager, pull requests merged in 2022-11, with the labels that each got.

#165 :seedling: add SECURITY_CONTACTS file
  SECURITY_CONTACTS
Labels: approved, lgtm, size/S

#167 🌱 Uplift CAPI to v1.2.5
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#168 🌱 Uplift CAPI to v1.2.5
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#171 🌱 Uplift CAPI to v1.2.6
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#170 🌱 Uplift CAPI to v1.3.0-rc.0 in main branch
  go.mod
  go.sum
Labels: approved, lgtm, size/M
