Repository metal3-io/ip-address-manager, pull requests merged in 2022-02, with the labels that each got.

#85 ⚠️ Default LeaderElectionResourceLock to leases
  config/rbac/leader_election_role.yaml
  main.go
Labels: approved, lgtm, size/M

#88 ✨ Uplift controller-tools to v0.8.0 and Uplift cluster-api to v1.1.0-rc.0
  config/crd/bases/ipam.metal3.io_ipaddresses.yaml
  config/crd/bases/ipam.metal3.io_ipclaims.yaml
  config/crd/bases/ipam.metal3.io_ippools.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/L

#90 ✨ Uplift CAPI to v0.4.7 in release-0.1 branch
  api/go.mod
  api/go.sum
  config/crd/bases/ipam.metal3.io_ipaddresses.yaml
  config/crd/bases/ipam.metal3.io_ipclaims.yaml
  config/crd/bases/ipam.metal3.io_ippools.yaml
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/L

#89 ✨ Uplifting CAPI to v1.1.0
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#92 ✨ Update CI badges with Metal3
  README.md
Labels: approved, lgtm, size/XS

#93 ✨ Update CI badges with Metal3
  README.md
Labels: approved, lgtm, size/XS

#94 ✨ Update CI badges with Metal3
  README.md
Labels: lgtm, size/XS

#96 ✨ Uplift cluster-api to v1.1.1
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#95 :seedling: Remove russellb as active approver
  OWNERS
Labels: approved, lgtm, size/XS

#97 🐛 Uplift docker/distribution to v2.8.0
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#98 🌱 Allow GA releases to trigger on v* tags
  .github/workflows/release.yaml
Labels: approved, lgtm, size/XS

#99 🌱 Add $(KUSTOMIZE) binary installation in release-manifests
  Makefile
Labels: approved, lgtm, size/XS

#100 ✨ Update: Capi to v1.1.2, controller runtime to v0.11.1, cert-manager URL and version to v1.5.3 and Kustomize to v4.4.1
  api/go.mod
  api/go.sum
  examples/generate.sh
  go.mod
  go.sum
  hack/ensure-kustomize.sh
  hack/tools/install_kustomize.sh
Labels: approved, lgtm, size/S

#103 🌱 Parameterize api folder path in Makefile and update kubectl/k8s versions under hack folder files
  Makefile
  hack/ensure-kubectl.sh
  hack/fetch_ext_bins.sh
Labels: approved, lgtm, size/S

#102 📖 Update root README compatibility table
  README.md
Labels: approved, lgtm, size/XS
