Repository metal3-io/ip-address-manager, pull requests merged in 2022-06, with the labels that each got.

#116 🌱 Uplift CAPI to v1.1.4 and k8s.io/api* modules to v0.23.5 in main branch
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#117 🌱 Uplift CAPI module to v0.4.8 in release-0.1 branch
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#118 🌱 Uplift github.com/docker/distribution v2.8.1
  go.mod
  go.sum
Labels: approved, lgtm, size/S
