Repository metal3-io/ip-address-manager, pull requests merged in 2023-09, with the labels that each got.

#309 :book: update README.md on 1.5 release
  README.md
Labels: approved, lgtm, size/XS

#308 :book: update README.md
  README.md
Labels: approved, lgtm, size/XS

#310 📖 improve release notes tool
  hack/tools/release/notes.go
Labels: approved, lgtm, size/S

#315 📖 update releasing.md
  docs/releasing.md
Labels: approved, lgtm, size/M

#320 🌱 run dependabot less often for GH actions
  .github/dependabot.yml
Labels: approved, lgtm, size/XS

#323 🐛 fix ensure-golangci-lint digest for Linux/amd64
  hack/ensure-golangci-lint.sh
Labels: approved, lgtm, size/S

#324 🌱 bump gosec to 2.17.0, and fix gosec for submodules
  .golangci.yaml
  hack/gosec.sh
Labels: approved, lgtm, size/S

#325 🌱 don't ignore #nosec in golangci-lint config
  .golangci.yaml
Labels: approved, lgtm, size/XS

#326 🌱 remove hack/gosec.sh
  hack/gosec.sh
Labels: approved, lgtm, size/S

#329 🌱 bump gosec and fix errors
  .github/workflows/golangci-lint.yml
  .golangci.yaml
  hack/ensure-golangci-lint.sh
  hack/gosec.sh
Labels: approved, lgtm, size/S

#331 📖 fix releasing.md on annotated tags
  docs/releasing.md
Labels: approved, lgtm, size/XS

#333 🌱 Bumping CAPI to 1.4.7
  Dockerfile
  examples/generate.sh
  go.mod
  go.sum
  hack/ensure-go.sh
Labels: approved, lgtm, size/S

#332 🌱 Bumping CAPI to 1.5.2
  Dockerfile
  Makefile
  examples/generate.sh
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#334 🌱 Bumping CAPI to 1.5.2
  Dockerfile
  Makefile
  examples/generate.sh
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#335 📖 clarify tag usage in releasing.md
  docs/releasing.md
Labels: approved, lgtm, size/XS
