Repository metal3-io/ip-address-manager, pull requests merged in 2023-08, with the labels that each got.

#289 :seedling: Fix code quality issues in TLS configuration code
  main.go
Labels: approved, lgtm, size/S

#290 :seedling: bump x/net to v0.14.0
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/M

#291 :seedling: bump x/net to 0.14.0
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/M

#295 Bump CAPI to v1.4.5
  docs/releasing.md
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#296 Bump CAPI to v1.3.10
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#294 🌱 Bump golangci-lint to v1.54.2
  .github/workflows/golangci-lint.yml
  .golangci.yaml
  hack/ensure-golangci-lint.sh
Labels: approved, lgtm, size/S

#304 🌱 Bump controller-runtime to v0.15.2
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#297 🌱 Remove unnecessary replace blocks from go modules and update release document
  docs/releasing.md
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#305 🌱 bump golang build_image to 1.20.7
  Dockerfile
Labels: approved, lgtm, size/XS

#306 🌱 Bump CAPI to v1.5.1 and cert-manager to v1.12.3
  examples/generate.sh
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#307 🌱 Bump capi to v1.4.6 and cert-manager to v1.12.3
  examples/generate.sh
  go.mod
  go.sum
Labels: approved, lgtm, size/S
