Repository metal3-io/ip-address-manager, pull requests merged in 2023-06, with the labels that each got.

#231 :seedling: add fuzzing targets for IPAM
  go.mod
  go.sum
  test/fuzz/README.md
  test/fuzz/ippool_controller_fuzzer.go
  test/fuzz/ippool_manager_fuzzer.go
Labels: approved, lgtm, size/L

#254 🌱 Fix dependabot.yml yaml formatting
  .github/dependabot.yml
Labels: approved, lgtm, size/M

#255 🌱 update kubeconform to v0.6.2
  hack/manifestlint.sh
Labels: approved, lgtm, size/XS

#256 🐛 Add missing github-actions to dependabot.yml
  .github/dependabot.yml
Labels: approved, lgtm, size/XS

#266 🌱 Include all gomods in different directories for Dependabot
  .github/dependabot.yml
Labels: approved, lgtm, size/S

#267 Add support for mac (kustomize)
  hack/tools/install_kustomize.sh
Labels: approved, lgtm, size/XS, ok-to-test

#248 :sparkles: Add TLS configuration flags for IPAM
  main.go
  main_test.go
Labels: approved, lgtm, size/L

#276 :sparkles: Added TLS configuration flags for IPAM
  main.go
  main_test.go
Labels: approved, lgtm, size/L

#277 :bug: Disable TLS 1.0 and TLS 1.1
  main.go
Labels: approved, lgtm, size/S
