Repository metal3-io/ip-address-manager, pull requests merged in 2023-10, with the labels that each got.

#339 🌱 add hack/verify-release.sh script
  docs/releasing.md
  hack/verify-release.sh
Labels: approved, do-not-merge/hold, lgtm, size/XL

#341 🌱 add hack/verify-release.sh
  hack/verify-release.sh
Labels: approved, lgtm, size/XL

#340 🌱 add hack/verify-release.sh
  hack/verify-release.sh
Labels: approved, lgtm, size/XL

#342 🌱 fix hack/verify-release.sh module list printout
  hack/verify-release.sh
Labels: approved, lgtm, size/XS

#343 🌱 drop test tag from verify-release.sh
  hack/verify-release.sh
Labels: approved, lgtm, size/XS

#344 🐛 sync go.mod files
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/L

#345 🌱 use GLOBIGNORE to ignore hack/tools/go.mod in verify-release.sh
  hack/verify-release.sh
Labels: approved, lgtm, size/S

#347 🌱 use GLOBIGNORE to ignore hack/tools/go.mod in verify-release.sh
  hack/verify-release.sh
Labels: approved, lgtm, size/S

#346 🌱 use GLOBIGNORE to ignore hack/tools/go.mod in verify-release.sh
  hack/verify-release.sh
Labels: approved, lgtm, size/S

#353 🌱 bump x/net to 0.17.0
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/M

#352 🌱 bump x/net to 0.17.0
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/M

#357 🌱 Bump golang version to v1.20.10 on release-1.5
  Dockerfile
  Makefile
Labels: approved, lgtm, size/XS, ok-to-test

#356 🌱 Bump golang to v1.20.10
  Dockerfile
  Makefile
Labels: approved, lgtm, size/XS, ok-to-test

#358 🌱 Bump golang version to 1.20.10 on release-1.4
  Dockerfile
Labels: approved, lgtm, size/XS, ok-to-test

#367 🌱 Bump CAPI to v1.4.8
  go.mod
  go.sum
Labels: approved, lgtm, size/XS
