Repository metal3-io/ip-address-manager, pull requests merged in 2023-12, with the labels that each got.

#398 ✨ Bump cluster-api to v1.6.0
  Makefile
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/ipam.metal3.io_ipaddresses.yaml
  config/crd/bases/ipam.metal3.io_ipclaims.yaml
  config/crd/bases/ipam.metal3.io_ippools.yaml
  config/manager/manager.yaml
  config/manager/manager_prometheus_metrics_patch.yaml
  config/rbac/role.yaml
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  main.go
Labels: approved, lgtm, size/XL

#399 🌱 add clomonitor badge to README
  README.md
Labels: approved, lgtm, size/XS

#403 🌱 add OpenSSF Scorecard badge to README
  README.md
Labels: approved, lgtm, size/XS

#400 🌱 Use k8s apimachinery scheme builder instead of controller-runtime scheme builder
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/ipaddress_types.go
  api/v1alpha1/ipclaim_types.go
  api/v1alpha1/ippool_types.go
  api/v1alpha1/v1alpha4_suite_test.go
Labels: approved, lgtm, size/S
