Repository metal3-io/ip-address-manager, pull requests merged in 2023-01, with the labels that each got.

#185 🌱 manifestlint: move from kubeval to kubeconform
  hack/manifestlint.sh
Labels: approved, lgtm, size/M

#186 🐛 .github: secure github actions
  .github/workflows/kubesec.yml
  .github/workflows/release.yaml
Labels: approved, lgtm, size/M

#193 🌱 uplift and pin golang 1.19.4 with digest
  Dockerfile
Labels: approved, lgtm, size/XS

#194 🌱 use docker.io consistently, and pin more checks
  hack/codegen.sh
  hack/gofmt.sh
  hack/gomod.sh
  hack/gosec.sh
  hack/govet.sh
  hack/markdownlint.sh
Labels: approved, lgtm, size/S

#189 🌱 Uplift CAPI to v1.3.2
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#191 🌱 Uplift CAPI to v1.2.9
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#188 🌱 Uplift CAPI to v1.3.2
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#195 ✨ add explicit securitycontexts to controller
  config/manager/manager.yaml
Labels: approved, lgtm, size/M
