Repository metal3-io/ip-address-manager, pull requests merged in 2023-05, with the labels that each got.

#237 🌱 pin distroless/static:nonroot to a sha digest
  Dockerfile
Labels: approved, lgtm, size/XS

#239 🌱 Bump CAPI to v1.4.2
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#240 🌱 Bump CAPI to v1.3.7
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#238 ✨ Add flags for configuring rate limits
  .gitignore
  main.go
Labels: approved, lgtm, size/S

#242 :seedling: bump golang image from 1.19.6 to 1.19.9
  Dockerfile
Labels: approved, lgtm, size/XS

#243 🌱 bump golang image from 1.19.6 to 1.19.9, pin distroless
  Dockerfile
Labels: approved, lgtm, size/XS

#246 🌱 Bump controller-tools to v0.11.4
  config/crd/bases/ipam.metal3.io_ipaddresses.yaml
  config/crd/bases/ipam.metal3.io_ipclaims.yaml
  config/crd/bases/ipam.metal3.io_ippools.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/L

#245 🌱 Bump controller-tools to v0.11.4
  config/crd/bases/ipam.metal3.io_ipaddresses.yaml
  config/crd/bases/ipam.metal3.io_ipclaims.yaml
  config/crd/bases/ipam.metal3.io_ippools.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/S

#250 🌱 Add dependabot configuration
  .github/dependabot.yml
Labels: approved, lgtm, size/M

#252 🌱 remove mdlrc and fix the one error it ignored
  .mdlrc
  README.md
Labels: approved, lgtm, size/XS
