Repository metal3-io/ip-address-manager, pull requests merged in 2023-04, with the labels that each got.

#213 ✨ Enable concurrency in ipam controllers
  controllers/ippool_controller.go
  main.go
Labels: approved, lgtm, size/S

#226 🌱 cleanup hack/ scripts
  hack/codegen.sh
  hack/ensure-go.sh
  hack/ensure-golangci-lint.sh
  hack/ensure-kind.sh
  hack/ensure-kubectl.sh
  hack/ensure-kustomize.sh
  hack/fetch_ext_bins.sh
  hack/gofmt.sh
  hack/gomod.sh
  hack/gosec.sh
  hack/govet.sh
  hack/kind_with_registry.sh
  hack/manifestlint.sh
  hack/markdownlint.sh
  hack/shellcheck.sh
  hack/tools/install_kubebuilder.sh
  hack/tools/install_kustomize.sh
  hack/unit.sh
  hack/verify-boilerplate.sh
Labels: approved, lgtm, size/XL

#227 🌱 Disable scheduled workflows from running in forks
  .github/workflows/kubesec.yml
  .github/workflows/release.yaml
Labels: approved, lgtm, size/XS

#229 📖 fix broken links in markdown files
  VERSIONING.md
  docs/api.md
Labels: approved, lgtm, size/XS

#225 📖 update releasing.md
  docs/releasing.md
Labels: approved, lgtm, size/L

#232 🌱 update build badges and compatibility table
  README.md
Labels: approved, lgtm, size/XS

#233 🌱 update build badges to point to 1.3
  README.md
Labels: approved, lgtm, size/XS

#235 🌱 update compatibility table in README.md
  README.md
Labels: approved, lgtm, size/XS
