Repository metal3-io/ip-address-manager, pull requests merged in 2024-01, with the labels that each got.

#407 🌱 bump k8s.io and controller-runtime Go modules to sync
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/L

#408 🌱 reduce github action permissions
  .github/workflows/build-images-action.yml
  .github/workflows/dependabot.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/kubesec.yml
  .github/workflows/lint-docs.yaml
  .github/workflows/pr-verifier.yaml
  .github/workflows/release.yaml
Labels: approved, lgtm, size/L

#394 🌱 Add tag triggering for container building wf
  .github/workflows/build-images-action.yml
Labels: approved, lgtm, size/XS

#409 🌱 bump golang to 1.20.12
  Dockerfile
  Makefile
Labels: approved, lgtm, size/XS

#410 🌱 remove some conditionals from workflows
  .github/workflows/build-images-action.yml
  .github/workflows/dependabot.yml
  .github/workflows/lint-docs.yaml
  .github/workflows/pr-verifier.yaml
Labels: approved, lgtm, size/XS

#415 🌱 fix dependabot workflow permissions
  .github/workflows/dependabot.yml
Labels: approved, lgtm, size/XS

#416 🌱 Bump CAPI to v1.6.1
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#417 🌱 Bump CAPI to v1.5.5
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#419 :book: switch markdownlint container to markdownlint-cli2
  .markdownlint-cli2.yaml
  VERSIONING.md
  hack/markdownlint.sh
  test/fuzz/README.md
Labels: approved, lgtm, size/M
