Repository metal3-io/ip-address-manager, pull requests merged in 2024-05, with the labels that each got.

#516 🌱 Set ARCH based on go env
  Makefile
Labels: approved, lgtm, size/XS

#506 🌱 Update Kustomize deprecated syntax
  config/certmanager/certificate.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_ipaddresses.yaml
  config/crd/patches/cainjection_in_ipclaims.yaml
  config/crd/patches/cainjection_in_ippools.yaml
  config/default/kustomization.yaml
  config/default/manager_webhook_patch.yaml
  config/default/webhookcainjection_patch.yaml
  config/manager/kustomization.yaml
  examples/provider-components/kustomization.yaml
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: approved, size/XXL, lgtm, ok-to-test

#520 🌱 Add Slack notification for image build workflow failure
  .github/workflows/build-images-action.yml
Labels: approved, lgtm, size/S

#522 🌱 move furkatgofurov7 to emeritus approvers
  OWNERS
Labels: approved, lgtm, size/XS, ok-to-test

#521 🌱 set webhook min TLS version to 1.3
  main.go
Labels: approved, lgtm, size/XS

#527 🌱 Extend the approvers and reviewers list
  OWNERS
Labels: approved, lgtm, size/S

#492 🌱 Add OSV scanner PR and schedule workflows
  .github/workflows/osv-scanner-scan.yml
  .github/workflows/osv-scanner.yml
Labels: approved, lgtm, size/L

#530 🌱 Bump CAPI to v1.7.2
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#532 🌱 bump protobuf to v1.33.0
  api/go.mod
  api/go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/S

#531 🌱 Bump CAPI v1.6.5
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#534 🌱 add OWNERS_ALIASES support
  OWNERS
  OWNERS_ALIASES
Labels: approved, lgtm, size/S

#544 🌱 remove kubesec workflow
  .github/workflows/kubesec.yml
Labels: approved, lgtm, size/M

#542 :seedling: explicitly drop pr approver workflow permissions
  .github/workflows/pr-gh-workflow-approve.yaml
Labels: approved, lgtm, size/XS
