Repository metal3-io/ip-address-manager, pull requests merged in 2024-03, with the labels that each got.

#437 🌱 Bump CAPI to v1.6.2
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/S

#441 🌱 Fix Ginkgo API test suite
  api/go.mod
  api/v1alpha1/suite_test.go
  api/v1alpha1/v1alpha4_suite_test.go
Labels: approved, lgtm, size/L

#444 🌱 add build images action to release-1.5
  .github/workflows/build-images-action.yml
Labels: approved, lgtm, size/M

#442 🌱Adjust and sync versions in go mod files
  api/go.mod
  api/go.sum
Labels: approved, lgtm, size/M

#446 🌱 Bump golang to v1.21.7
  Dockerfile
  Makefile
Labels: approved, lgtm, size/XS

#447 🌱 Bump golang to v1.21.7
  Dockerfile
  Makefile
Labels: approved, lgtm, size/XS

#445 🌱 fix build image action for release-1.6
  .github/workflows/build-images-action.yml
Labels: approved, lgtm, size/M

#448 🌱 Bump golangci-lint to v1.56.2
  .github/workflows/golangci-lint.yml
  .golangci.yaml
  hack/ensure-golangci-lint.sh
Labels: approved, lgtm, size/S

#443 :seedling: Add make unit-cover like in BMO
  Makefile
Labels: approved, lgtm, size/S, ok-to-test

#451 🌱 bump shellcheck to v0.10.0
  hack/shellcheck.sh
Labels: approved, lgtm, size/XS

#450 🌱 add golang base image check to verify-release.sh
  hack/verify-release.sh
Labels: approved, lgtm, size/M

#458 🌱 Bump CAPI to v1.6.3
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#459 :seedling: bump CAPI to v1.5.7
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#467 🌱 Bump CAPI to v1.7.0-beta.0
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#449 🌱 Improve ipv6 address in bound check performance in ippool webhook
  api/v1alpha1/ippool_webhook.go
  api/v1alpha1/ippool_webhook_test.go
Labels: approved, lgtm, size/M, ok-to-test

#473 🌱 remove obsolete Makefile related gofmt, govet scripts
  Makefile
  hack/gofmt.sh
  hack/govet.sh
Labels: approved, lgtm, size/M, ok-to-test

#475 🌱 add support for beta/rc releases in release notes
  .github/workflows/release.yaml
  Makefile
  hack/tools/release/notes.go
Labels: approved, lgtm, size/M

#472 🌱 bump golang to 1.21.8
  Dockerfile
  Makefile
Labels: approved, lgtm, size/XS

#478 🌱 Bump CAPI to v1.7.0-beta.1
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#479 :book: update releasing docs
  docs/releasing.md
Labels: approved, lgtm, size/M
