Repository metal3-io/ip-address-manager, pull requests merged in 2024-12, with the labels that each got.

#776 :seedling: Bump CAPI to v1.9.0-rc.1 and controller-runtime to v0.19.3
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#777 :seedling: Lint hack/tools
  .github/workflows/golangci-lint.yml
  Makefile
  hack/tools/release/notes.go
Labels: approved, lgtm, size/L, ok-to-test

#775 :bug: Make image build on releases
  .github/workflows/build-images-action.yml
Labels: approved, lgtm, size/M

#784 :seedling: Bump capi to v1.8.6
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#783 :seedling: Bump capi to v1.7.9
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#782 :seedling: Bump CAPI to v1.9.0
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#785 :seedling: Bump Golang to v1.23.4
  Dockerfile
  Makefile
Labels: approved, lgtm, size/XS

#788 :rocket: Release v1.9.0
  releasenotes/v1.9.0.md
Labels: approved, lgtm, size/M

#789 :seedling: Fix container image build workflow
  .github/workflows/build-images-action.yml
Labels: approved, lgtm, size/M

#806 🌱 Bump CAPI to v1.9.1
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#808 🚀 Release v1.9.1
  releasenotes/v1.9.1.md
Labels: approved, lgtm, size/S

#809 :book: add adilGhaffarDev as reviewer
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#813 :book: update build badges for release-1.9
  README.md
Labels: approved, size/XS

#815 :seedling: backport container build image wf to release-1.8 branch
  .github/workflows/build-images-action.yml
Labels: approved, lgtm, size/S

#816 :seedling: Backport container build image wf to release-1.7
  .github/workflows/build-images-action.yml
Labels: approved, lgtm, size/S

#820 :seedling: remove old release automation
  .github/workflows/release.yaml
Labels: approved, lgtm, size/M

#786 :bug: Fix release-notes in Makefile
  Makefile
  docs/releasing.md
  hack/tools/release/notes.go
Labels: approved, lgtm, size/S

#819 :seedling: remove old release automation
  .github/workflows/release.yaml
Labels: approved, lgtm, size/M

#817 🌱 Bump sigs.k8s.io/kustomize/kustomize/v5 to 5.5.0
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/M

#818 :rocket: Add v1.7.4 release note
  releasenotes/v1.7.4.md
Labels: approved, lgtm, size/S
