Repository metal3-io/ip-address-manager, pull requests merged in 2024-11, with the labels that each got.

#728 🌱 Use OSV-Scanner release binary and Reporter action workflow instead of pointing to a file
  .github/workflows/osv-scanner-scan.yml
Labels: approved, lgtm, size/M

#737 🌱 Bump CAPI to v1.7.8
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#736 🌱 Bump CAPI to v1.8.5
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#745 🌱 Increase time for golint test to avoid timeout failure
  Makefile
Labels: approved, lgtm, size/XS

#743 🌱 Bump Golang to 1.22.9
  Dockerfile
  Makefile
Labels: approved, lgtm, size/XS

#744 :seedling: Bump Golang to 1.22.9
  Dockerfile
  Makefile
Labels: approved, lgtm, size/XS

#742 🌱 Bump Golang to 1.22.9
  Dockerfile
  Makefile
Labels: approved, lgtm, size/XS

#695 :seedling: add osv-scanner config for correcting go version used
  .github/workflows/osv-scanner-scan.yml
Labels: approved, lgtm, size/M

#741 :seedling: use make go-version instead of Dockerfile parsing in verify-release.sh
  hack/verify-release.sh
Labels: approved, lgtm, size/M

#749 :seedling: bump Go to 1.23.3 and golangci-lint to 1.60.3
  .github/workflows/golangci-lint.yml
  .golangci.yaml
  Dockerfile
  Makefile
  hack/ensure-golangci-lint.sh
  ipam/ippool_manager.go
Labels: approved, lgtm, size/M

#735 🌱 Bump CAPI to v1.9.0-beta.0
  controllers/ippool_controller.go
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#734 🌱 Automating release creation
  .github/workflows/release.yaml
  .gitignore
  Makefile
  docs/releasing.md
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/release/notes.go
Labels: approved, lgtm, size/L

#762 🌱 Fixing go mod mismatches
  api/go.mod
  api/go.sum
  config/crd/bases/ipam.metal3.io_ipaddresses.yaml
  config/crd/bases/ipam.metal3.io_ipclaims.yaml
  config/crd/bases/ipam.metal3.io_ippools.yaml
  config/rbac/role.yaml
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/XL

#765 🌱 Fix make release target
  Makefile
Labels: approved, lgtm, size/XS

#766 🌱 Fix make release target
  Makefile
Labels: approved, lgtm, size/XS

#764 🌱 Fixing release note generation
  Makefile
  hack/tools/release/notes.go
Labels: approved, lgtm, size/M

#768 🚀 Release v1.7.3
  releasenotes/v1.7.3.md
Labels: approved, lgtm, size/S
