Repository metal3-io/ip-address-manager, pull requests merged in 2024-04, with the labels that each got.

#484 🌱 Bump CAPI to v1.7.0-rc.0
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#485 🌱 add workflow to approve actions on PR change
  .github/workflows/pr-gh-workflow-approve.yaml
Labels: approved, lgtm, size/M

#487 🌱 Bump golang.org/x/net to v0.23.0 and golang to v1.21.9
  Dockerfile
  Makefile
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#489 🌱 Bump CAPI to v1.7.0-rc.1
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#491 🌱 Bump golang.org/x/net to v0.24.0 and golang to v1.21.9
  Dockerfile
  Makefile
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/M

#490 🌱 Bump golang.org/x/net to v0.24.0 and golang to v1.21.9
  Dockerfile
  Makefile
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/M

#497 🌱 Bump CAPI to v1.7.0
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#498 🌱 Bump CAPI to v1.5.8
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#499 🌱 Bump CAPI to v1.6.4
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#500 :seedling: Fix package versions mismatches
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/L

#504 🌱 Update build badges for release-1.7
  README.md
Labels: approved, lgtm, size/XS, ok-to-test

#505 🌱 bump CAPI to v1.7.1
  go.mod
  go.sum
Labels: approved, lgtm, size/XS, ok-to-test

#508 🌱 improve hack/verify-release.sh
  hack/verify-release.sh
Labels: approved, lgtm, size/M, ok-to-test
