Repository metal3-io/ip-address-manager, pull requests merged in 2024-06, with the labels that each got.

#556 🌱 bump golang to 1.21.11
  Dockerfile
  Makefile
Labels: approved, lgtm, size/XS

#558 🌱 bump golang to 1.22.4
  Dockerfile
  Makefile
Labels: approved, lgtm, size/XS

#560 🌱 bump capi to 1.7.3
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#559 🌱 bump CAPI to 1.7.3
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#562 🌱 bump k8s.io/code-generator to v0.30.2
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/M

#564 🌱 Bump CAPI to 1.6.6
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#563 :seedling: Bump k8s.io/* to v0.30.2 and controller-runtime to v0.18.4
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#565 📖 add openssf best practices badge to README
  README.md
Labels: approved, lgtm, size/XS

#539 🌱 Optimize the dependabot configuration and add release branch configurations.
  .github/dependabot.yml
Labels: approved, lgtm, size/L
