Repository metal3-io/ip-address-manager, pull requests merged in 2024-08, with the labels that each got.

#626 🌱 Bump CAPI to v1.8.0-rc.1
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#628 :seedling: Move container build job to GH runner
  .github/workflows/build-images-action.yml
Labels: approved, lgtm, size/M

#629 :seedling: Container build wf only run for upstream
  .github/workflows/build-images-action.yml
Labels: approved, lgtm, size/XS

#630 🌱 Set terminationMessagePolicy to FallbackToLogsOnError for manager
  config/manager/manager.yaml
Labels: approved, lgtm, size/M

#639 🌱 Uplift CAPI to 1.8.0 and Drop caBundle from CRDs
  api/go.mod
  api/go.sum
  config/crd/patches/webhook_in_ipaddresses.yaml
  config/crd/patches/webhook_in_ipclaims.yaml
  config/crd/patches/webhook_in_ippools.yaml
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#643 🌱 fix verify-release.sh to understand go directive better
  hack/verify-release.sh
Labels: approved, lgtm, size/XS

#641 🌱 Bump CAPI to v1.8.1
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#642 🌱 bump golang to 1.22.6
  Dockerfile
  Makefile
Labels: approved, lgtm, size/XS

#652 :seedling: Bump kustomize to v5.4.3
  hack/tools/install_kustomize.sh
Labels: approved, lgtm, size/XS

#657 🌱 add dependabot config for release-1.8
  .github/dependabot.yml
Labels: approved, lgtm, size/M

#672 🌱 fix dependabot config ignore rules
  .github/dependabot.yml
Labels: approved, lgtm, size/S
