Repository metal3-io/ip-address-manager, pull requests merged in 2024-09, with the labels that each got.

#675 🌱 remove release-1.6 from dependabot
  .github/dependabot.yml
Labels: approved, lgtm, size/M

#678 :book: Update missing releases in compatibility table
  README.md
Labels: approved, lgtm, size/XS

#677 :book: Update build badges for release-1.8
  README.md
Labels: approved, lgtm, size/XS

#676 🌱 Use osv-scanner workflow file instead of local workflow
  .github/workflows/osv-scanner-scan.yml
  .github/workflows/osv-scanner.yml
Labels: approved, lgtm, size/L

#681 🌱 bump golang to 1.22.7
  Dockerfile
  Makefile
Labels: approved, lgtm, size/XS

#683 🌱 Bump CAPI to v1.7.6
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#682 🌱 Bump CAPI to v1.8.3
  go.mod
  go.sum
Labels: approved, lgtm, size/XS
