Repository metal3-io/ip-address-manager, pull requests merged in 2024-07, with the labels that each got.

#588 📖 Document backporting rules for Go lang minor versions for images
  CONTRIBUTING.md
Labels: approved, lgtm, size/M

#593 🌱 schedule dependabot on certain day, and add ok-to-test automatically
  .github/dependabot.yml
Labels: approved, lgtm, size/M

#598 🌱 bump golang to 1.22.5
  Dockerfile
  Makefile
Labels: approved, lgtm, size/XS

#600 🌱 Bump CAPI to v1.7.4
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#606 🌱 Bump CAPI to v1.8.0-beta.0
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#612 🌱 Uplift CAPI to v1.8.0-beta.1
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#607 🌱 Bump golang to v1.22
  .github/workflows/release.yaml
  .golangci.yaml
  Dockerfile
  Makefile
  api/go.mod
  go.mod
  hack/codegen.sh
  hack/gomod.sh
  hack/tools/go.mod
  hack/unit.sh
Labels: approved, lgtm, size/S, ok-to-test

#616 :seedling: Bump golang to 1.22 in release 1.6
  .github/workflows/release.yaml
  .golangci.yaml
  Dockerfile
  Makefile
  controllers/ippool_controller_test.go
  hack/codegen.sh
  hack/gofmt.sh
  hack/gomod.sh
  hack/govet.sh
  hack/unit.sh
Labels: approved, lgtm, size/M

#617 🌱 Uplift CAPI to v1.8.0-rc.0
  go.mod
  go.sum
  main.go
  main_test.go
Labels: approved, lgtm, size/L
