Repository metal3-io/ip-address-manager, pull requests merged in 2025-09, with the labels that each got.

#1118 🌱 Bump github.com/onsi/gomega to v1.38.2
  api/go.mod
  api/go.sum
Labels: approved, lgtm, size/XS

#1127 :rocket: Release v1.11.0-rc.0
  releasenotes/v1.11.0-rc.0.md
Labels: approved, lgtm, size/M

#1128 :rocket: Release v1.10.2
  releasenotes/v1.10.2.md
Labels: approved, lgtm, size/S

#1130 📖 Add alpha release in release documentation
  docs/releasing.md
Labels: approved, lgtm, size/XS

#1148 :seedling: Bump golang to v1.24.7
  Dockerfile
  Makefile
Labels: approved, lgtm, size/XS

#1151 📖 update build badges for release-1.11
  README.md
Labels: approved, lgtm, size/XS

#1154 📖 Update compatibility matrix
  README.md
Labels: approved, lgtm, size/XS

#1162 :seedling: add specific time to dependabot config
  .github/dependabot.yml
Labels: approved, lgtm, size/S
