Repository metal3-io/ip-address-manager, pull requests merged in 2025-06, with the labels that each got.

#1043 🌱 Bump golang to v1.24
  .golangci.yaml
  Dockerfile
  Makefile
  hack/codegen.sh
  hack/gomod.sh
  hack/unit.sh
Labels: approved, lgtm, size/S

#1051 :seedling: Enable variable shadowing check in govet linter
  .golangci.yaml
  controllers/ippool_controller.go
  ipam/ippool_manager.go
  ipam/utils_test.go
Labels: approved, lgtm, size/M

#1056 :bug: Fix set-manifest-image rule
  Makefile
Labels: approved, lgtm, size/XS
