Repository metal3-io/ip-address-manager, pull requests merged in 2025-02, with the labels that each got.

#885 :seedling: workflows: sync pull_request trigger types
  .github/workflows/golangci-lint.yml
  .github/workflows/lint-docs.yaml
  .github/workflows/pr-gh-workflow-approve.yaml
  .github/workflows/pr-verifier.yaml
Labels: approved, lgtm, size/S

#888 :seedling: pin osv-scanner image in verify-release.sh
  hack/verify-release.sh
Labels: approved, lgtm, size/XS

#900 :seedling: Bump CAPI to 1.8.10
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#901 :seedling: Bump CAPI to 1.9.5
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#903 :rocket: Release v1.8.5
  releasenotes/v1.8.5.md
Labels: approved, lgtm, size/S

#904 :rocket: Release v1.9.4
  releasenotes/v1.9.4.md
Labels: approved, lgtm, size/S

#692 ⚠️ Make ip-address-manager an IPAM provider for CAPI
  Dockerfile
  Makefile
  README.md
  config/default/kustomization.yaml
  config/manager/manager.yaml
  config/rbac/role.yaml
  controllers/ippool_controller.go
  controllers/ippool_controller_test.go
  controllers/suite_test.go
  docs/api.md
  examples/generate.sh
  examples/ippool/ippool.yaml
  examples/provider-components/manager_tolerations_patch.yaml
  ipam/ippool_manager.go
  ipam/ippool_manager_test.go
  ipam/suite_test.go
  main.go
  metadata.yaml
Labels: approved, size/XXL, lgtm
