Repository metal3-io/ip-address-manager, pull requests merged in 2025-03, with the labels that each got.

#911 :bug: bump actions/cache to v4.2.2
  .github/workflows/dependabot.yml
Labels: approved, lgtm, size/XS

#912 :bug: bump actions/cache to v4.2.2
  .github/workflows/dependabot.yml
Labels: approved, lgtm, size/XS

#923 :seedling: fix dependabot testing issues by re-adding "edited"
  .github/workflows/golangci-lint.yml
  .github/workflows/lint-docs.yaml
  .github/workflows/pr-gh-workflow-approve.yaml
  .github/workflows/pr-verifier.yaml
Labels: approved, lgtm, size/XS

#928 :seedling: bump x/net and x/oauth2
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/L

#927 :seedling: bump x/oauth2 to v0.27.0
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#929 :seedling: bump x/net and x/oauth2
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/L

#934 :seedling: group all github action bumps into single PR
  .github/dependabot.yml
Labels: approved, lgtm, size/M

#939 :seedling: bump tj-actions/changed-files to v46.0.1
  .github/workflows/release.yaml
Labels: approved, lgtm, size/XS

#941 🌱 bump CAPI v1.10.0-beta.0
  api/go.mod
  api/go.sum
  api/v1alpha1/ipaddress_webhook.go
  api/v1alpha1/ipaddress_webhook_test.go
  api/v1alpha1/ipclaim_webhook.go
  api/v1alpha1/ipclaim_webhook_test.go
  api/v1alpha1/ippool_webhook.go
  api/v1alpha1/ippool_webhook_test.go
  go.mod
  go.sum
Labels: approved, lgtm, size/XL

#942 🌱 Bump golangci-lint to v1.64.7
  .github/workflows/golangci-lint.yml
  .golangci.yaml
  hack/ensure-golangci-lint.sh
Labels: approved, lgtm, size/S

#943 :seedling: update osv-scanner to v2.0.0
  .github/workflows/osv-scanner-scan.yml
  hack/verify-release.sh
Labels: approved, lgtm, size/M

#956 🌱 Bump kustomize to 5.6.0 and code-generator to 0.32.3
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/L

#957 :seedling: Bump CAPI to 1.10.0-beta.1
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#968 :rocket: Release v1.10.0-beta.0
  releasenotes/v1.10.0-beta.0.md
Labels: approved, lgtm, size/M

#958 :seedling: update the used linters list
  .golangci.yaml
Labels: approved, lgtm, size/M

#970 :seedling: Enable ginkgolinter
  .golangci.yaml
  controllers/ippool_controller_test.go
  ipam/ippool_manager_test.go
  ipam/utils_test.go
Labels: approved, lgtm, size/M, ok-to-test
