Repository metal3-io/ip-address-manager, pull requests merged in 2025-04, with the labels that each got.

#972 🌱 Enable errname, forbidigo, forcetypeassert, mnd, perfsprint and unparam linters
  .golangci.yaml
  api/v1alpha1/utils_test.go
  controllers/ippool_controller_test.go
  controllers/suite_test.go
  hack/tools/release/notes.go
  ipam/ippool_manager.go
  ipam/ippool_manager_test.go
  ipam/manager_factory_test.go
  ipam/reconcile_error.go
  ipam/reconcile_error_test.go
  ipam/suite_test.go
  ipam/utils.go
  ipam/utils_test.go
  main.go
  test/fuzz/ippool_controller_fuzzer.go
  test/fuzz/ippool_manager_fuzzer.go
Labels: approved, lgtm, size/L, ok-to-test

#975 :seedling: move mquhuy to emeritus reviewers
  OWNERS
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#976 :seedling: do not bump major version of github actions
  .github/dependabot.yml
Labels: approved, lgtm, size/S

#984 :seedling: bump golang to v1.23.8 and x/net to v0.38.0
  Dockerfile
  Makefile
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/M

#983 :seedling: bump golang to v1.23.8 and x/net to v0.38.0
  Dockerfile
  Makefile
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/M

#982 :seedling: bump golang to v1.23.8 and x/net to v0.38.0
  Dockerfile
  Makefile
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/M

#987 :seedling: make osv-scanner scan run daily
  .github/workflows/osv-scanner-scan.yml
Labels: approved, lgtm, size/XS

#998 :seedling: Bump CAPI to v1.10.0-rc.0
  go.mod
  go.sum
Labels: approved, lgtm, size/S, ok-to-test

#1000 📖 Make Adil and Peppi maintainers
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#999 :seedling: Enable dupl linter
  .golangci.yaml
Labels: approved, lgtm, size/XS, ok-to-test

#1003 🌱 Set GITHUB_TOKEN in env in release workflow
  .github/workflows/release.yaml
Labels: approved, lgtm, size/XS

#996 📖 Limitation regarding IPClaim
  README.md
Labels: approved, lgtm, size/S

#997 ✨ Adding feature for allocating requested IP
  examples/ippool/ippool.yaml
  ipam/ippool_manager.go
  ipam/ippool_manager_test.go
Labels: approved, lgtm, size/L, ok-to-test

#1007 :seedling: Configure tagliatelle linter
  .golangci.yaml
Labels: approved, lgtm, size/XS

#1009 :rocket: Release v1.10.0
  releasenotes/v1.10.0.md
Labels: approved, lgtm, size/M

#1008 :seedling: Fix notes.go so that it still complies with forbidigo
  .golangci.yaml
  hack/tools/release/notes.go
Labels: approved, lgtm, size/S

#1015 :seedling: add dependabot config for release-1.10
  .github/dependabot.yml
Labels: approved, lgtm, size/S
