Repository metal3-io/ip-address-manager, pull requests merged in 2025-01, with the labels that each got.

#840 :seedling: Add build container image as a job in release wf
  .github/workflows/build-images-action.yml
  .github/workflows/release.yaml
Labels: approved, lgtm, size/S

#842 :seedling: Bump Golang to 1.23.4
  Dockerfile
  Makefile
Labels: approved, lgtm, size/XS

#844 :rocket: Release v1.8.3
  releasenotes/v1.8.3.md
Labels: approved, lgtm, size/S

#847 :seedling: bump kubeconform to v0.6.7
  hack/manifestlint.sh
Labels: approved, lgtm, size/XS

#850 :seedling: bump x/net to v0.34.0
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/M

#849 :seedling: bump x/net to v0.34.0
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, lgtm, size/M

#787 🌱 Introduce ReconcileError with Transient and Terminal Error type
  controllers/ippool_controller.go
  ipam/ippool_manager.go
  ipam/ippool_manager_test.go
  ipam/reconcile_error.go
  ipam/reconcile_error_test.go
  ipam/requeue_error.go
  ipam/requeue_error_test.go
  ipam/utils.go
  ipam/utils_test.go
Labels: approved, lgtm, size/L

#868 :book: update OpenSSF CII Best Practices badge
  README.md
Labels: approved, lgtm, size/XS

#869 :bug: bump golang to 1.23.5
  Dockerfile
  Makefile
Labels: approved, lgtm, size/XS

#871 :bug: bump golang to 1.23.5
  Dockerfile
  Makefile
Labels: approved, lgtm, size/XS

#870 :bug: bump golang to 1.23.5
  Dockerfile
  Makefile
Labels: approved, lgtm, size/XS

#873 :rocket: Release v1.9.3
  releasenotes/v1.9.3.md
Labels: approved, lgtm, size/S

#872 :rocket: Release v1.8.4
  releasenotes/v1.8.4.md
Labels: approved, lgtm, size/S
